[package]
name = "rust_cumulus"
version = "0.1.0"
authors = ["Wadjetz <egor.neon@gmail.com>"]

[profile.release]
#lto = true # Binary size optiomisation, but longuer compile time

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
juniper = { git = "https://github.com/stankec/juniper", features = ["rocket-handlers"] }

r2d2 = "0.7.3"
r2d2_postgres = "0.12.0"
postgres =  { version = "0.14.2", features = ["with-serde_json", "with-uuid", "with-chrono"] }
postgres-shared = "0.3.0"
postgres-protocol = "0.3.0"
postgres-derive = "0.3.1"
strum = "0.6.0"
strum_macros = "0.6.1"

serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"

uuid = { version = "0.5.1", features = ["serde", "v4"] }
chrono = "0.3.0"

lazy_static = "0.2.8"

#itertools = "0.6.0"

jsonwebtoken = "2.0.3"
bcrypt = "0.1.3"
rust-crypto = "0.2.36"

feed-rs = "0.1.3"
hyper = "0.11.1"
reqwest = "0.7.1"
url = "1.5.1"

dotenv = "0.10.1"

error-chain = "0.10.0"
