[package]
name = "rust_cumulus"
version = "0.1.0"
authors = ["Wadjetz <egor.neon@gmail.com>"]

[dependencies]
rocket = "0.2.8"
rocket_codegen = "0.2.8"
juniper = { git = "https://github.com/mhallin/juniper", features = ["rocket-handlers", "expose-test-schema"] }
