[package]
name = "rust_cumulus"
version = "0.1.0"
authors = ["Wadjetz <egor.neon@gmail.com>"]

[dependencies]
rocket = "0.2.8"
rocket_codegen = "0.2.8"
rocket_contrib = "0.2.8"
juniper = { version = "0.8.1", features = ["rocket-handlers"] }

r2d2 = "0.7.2"
r2d2_postgres = "0.12.0"
postgres =  { version = "0.14.2", features = ["with-uuid", "with-chrono"] }
postgres-shared = "0.3.0"

serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"

validator = "0.4.0"
validator_derive = "0.5.0"

uuid = { version = "0.5.0", features = ["serde", "v4"] }
chrono = "0.3.1"

jsonwebtoken = "2.0.1"
bcrypt = "0.1.3"

dotenv = "0.10.0"

error-chain = "0.10.0"

clippy = "0.0.140"
